package model.paint.strategy;

import java.awt.geom.AffineTransform;

import model.paint.ShapePaintStrategy;
import model.paint.shape.Fish2PolygonFactory;

/**
 * Paint strategy that paints a fish-shaped Polygon generated by a Fish2PolygonFactory.
 * @author Peter
 */
public class Fish2PaintStrategy extends ShapePaintStrategy {

	/**
	 * No-parameter constructor that instantiates the AffineTransform for internal use.
	 */
	public Fish2PaintStrategy() {
		this(new AffineTransform());
	}

	/**
	 * Constructor that takes an external AffineTransform.
	 * @param at The AffineTransform to use for internal use.
	 */
	public Fish2PaintStrategy(AffineTransform at) {
		super(at, new Fish2PolygonFactory().makeShape(0, 0, 1, 1));
	}
}
